import './globals.css'
import Navbar from '../components/navbar'
import { ClerkProvider } from '@clerk/nextjs'

export const metadata = {
  title: 'PnL',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="bg-blue-100">
          <Navbar></Navbar>
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
