import './globals.css';
import Navbar from '../components/navbar';
import { ClerkProvider } from '@clerk/nextjs';
import Wallet from '@/components/wallet';

export const metadata = {
  title: 'PnL',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="bg-blue-100">
          <Navbar></Navbar>
          <Wallet className=''></Wallet>
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
