import './globals.css'
import Navbar from '../components/navbar'

export const metadata = {
  title: 'PnL',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-blue-100">
        <Navbar></Navbar>
        {children}
      </body>
    </html>
  )
}
